image:
  repository: ghcr.io/sameem-s/go-hello-service
  tag: b6ea9f7
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /readyz
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 5
  failureThreshold: 3
